### ISSUE TITLE
Rogue lines on the map

### ISSUE THREAD

**Issue by hugovk** [marcusvolz/strava#14]
Plotting a map with latest master:

```r
# Install the packages
install.packages(c("devtools", "mapproj", "tidyverse"))
devtools::install_github("marcusvolz/strava")


# Load the libraries
library(strava)
library(tidyverse)

# Process the data
data <- process_data("data")

# Plot activity map
p2 <- plot_map(data, lon_min = 24.8312, lon_max = 25.2022, lat_min = 60.1301, lat_max = 60.2893)
ggsave("plots/map001.png", p2, width = 20, height = 15, units = "cm", dpi = 600)
```

Produces this map with unnecessary connecting lines:

![map001](https://user-images.githubusercontent.com/1324225/45474775-47cb5580-b743-11e8-86b2-fe25baa7d16c.png)

Using commit 4b15bef416955415759361ac10e227ca07c3fde6 from _before_ the last PR #13:

```r
# Only this line is changed
devtools::install_github("marcusvolz/strava", ref="4b15bef416955415759361ac10e227ca07c3fde6")

library(strava)
library(tidyverse)

data <- process_data("data")

p2 <- plot_map(data, lon_min = 24.8312, lon_max = 25.2022, lat_min = 60.1301, lat_max = 60.2893)
ggsave("plots/map001_4b15bef.png", p2, width = 20, height = 15, units = "cm", dpi = 600)

```

Produces this correct map:

![image](https://user-images.githubusercontent.com/1324225/45475325-ab09b780-b744-11e8-90dc-f361d19d1893.png)

Any ideas what's up?

I'm guessing https://github.com/marcusvolz/strava/pull/13/files#diff-5c21092021c5b63d9c4547469d073851L42 means it assumes all tracks start and end at the same point, which isn't always the case with cycling.

Ping @kkeenan02 :)

**Comment by scottieie** [comment]
Bad GPS reads. Started /stopped in different spot. Remove erroneous records
and redo. Call me. 8459017896

Pardon brevity and typos, sent by phone.

Scott Workman
Data Analyst, MCPD

===

"The future will either be green or not at all." - Bob Brown

On Sep 13, 2018 4:51 AM, "Hugo" <notifications@github.com> wrote:

Plotting a map with latest master:

# Install the packages
install.packages(c("devtools", "mapproj",
"tidyverse"))devtools::install_github("marcusvolz/strava")

# Load the libraries
library(strava)
library(tidyverse)
# Process the datadata <- process_data("data")
# Plot activity mapp2 <- plot_map(data, lon_min = 24.8312, lon_max =
25.2022, lat_min = 60.1301, lat_max = 60.2893)
ggsave("plots/map001.png", p2, width = 20, height = 15, units = "cm", dpi = 600)

Produces this map with unnecessary connecting lines:

[image: map001]
<https://user-images.githubusercontent.com/1324225/45474775-47cb5580-b743-11e8-86b2-fe25baa7d16c.png>

Using commit 4b15bef
<https://github.com/marcusvolz/strava/commit/4b15bef416955415759361ac10e227ca07c3fde6>
from *before* the last PR #13 <https://github.com/marcusvolz/strava/pull/13>
:

# Only this line is
changeddevtools::install_github("marcusvolz/strava",
ref="4b15bef416955415759361ac10e227ca07c3fde6")

library(strava)
library(tidyverse)
data <- process_data("data")
p2 <- plot_map(data, lon_min = 24.8312, lon_max = 25.2022, lat_min =
60.1301, lat_max = 60.2893)
ggsave("plots/map001_4b15bef.png", p2, width = 20, height = 15, units
= "cm", dpi = 600)

Produces this correct map:

[image: image]
<https://user-images.githubusercontent.com/1324225/45475325-ab09b780-b744-11e8-90dc-f361d19d1893.png>

Any ideas what's up?

I'm guessing
https://github.com/marcusvolz/strava/pull/13/files#diff-5c21092021c5b63d9c4547469d073851L42
means it assumes all tracks start and end at the same point, which isn't
always the case with cycling.

Ping @kkeenan02 <https://github.com/kkeenan02> :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/marcusvolz/strava/issues/14>, or mute the thread

**Comment by hugovk** [comment]
Thanks, I've confirmed that fixes it.
