### ISSUE TITLE
Facet Order?

### ISSUE THREAD

**Issue by CDunhill** [marcusvolz/strava#51]
Hi - love this package, thanks. Lots of fun to be had once I've filtered my runs out properly.

What order do the facets plot in? It doesn't _look_ like it's in date order - is this true? In which case do you have any idea how one might arrange them chronologically?

**Comment by marcusvolz** [comment]
Hi - Facets are ordered by activity file names, e.g. 478041523.gpx, 478041524.gpx, ... (where the file names are treated as numbers rather than strings for sorting). I expected that file numbers were ordered by date, but maybe that's not the case. Could you verify that your activity facets are out of order?

**Comment by CDunhill** [comment]
That makes sense - I will check. Either way it would be easy for me to rename them according to date. Thank you.
